
project_id = "pjoetqssccgixqnptytq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://pjoetqssccgixqnptytq.supabase.co", "https://45-days-fitness.dipnerreddy.in/reset-password"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Custom email template configuration for password reset
[auth.email.template.recovery]
subject = "🔒 Reset Your 45-Day Challenge Password"
content_path = "./supabase/templates/recovery.html"

# Custom email template for email confirmations
[auth.email.template.confirmation]
subject = "🔥 Welcome to the 45-Day Challenge!"

# Custom email template for magic links
[auth.email.template.magic_link]
subject = "🚀 Your Magic Login Link"

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54321
file_size_limit = "50MiB"

[edge-runtime]
enabled = true
port = 54321

[analytics]
enabled = false
port = 54327
vector_port = 54328

[functions.send-workout-reminders]
verify_jwt = false

[functions.reset-inactive-streaks]
verify_jwt = false
